version: '3.8'
services:
  front:
    #build: ./client
    container_name: client_frontend
    image: client_frontend
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    stdin_open: true
    tty: true